# This is a basic workflow to help you get started with Actions

name: Run Tutorial Build

# Controls when the action will run. Triggers the workflow pull request
# events on every branch
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  OSX_LINUX:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
          java-version: 11

    # Runs a single command using the runners shell
    - name: Build Tutorial
      run: ./gradlew build
    - uses: actions/upload-artifact@v2
      with:
        name: weave-tutorial
        path: build/distributions/*.zip
        retention-days: 90
    - uses: "marvinpinto/action-automatic-releases@latest"
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          LICENSE
          build/distributions/*.zip
